name: "CI"

on:
  - push
  - pull_request

jobs:
  tests:
    defaults:
      run:
        shell: bash
    name: "Run tests on Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.10', '3.9', '3.8']
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: false
    - name: Set up Python ${{ matrix.python-version }}
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Package
      run: |
        python -m pip install --upgrade pip
        python -m pip install . tox
    - name: Run tox tests
      run: tox
